import turtle
import math
import random
turtle.hideturtle()
turtle.bgcolor("black")
x = turtle.Pen()
y = turtle.Pen()
z = turtle.Pen()
a = turtle.Pen()
w = turtle.Pen()
b = turtle.Pen()
c = turtle.Pen()
d = turtle.Pen()
e = turtle.Pen()
stem = turtle.Pen()
ground = turtle.Pen()
#x.setposition(0,10)
#y.setposition(0,-10)

#x.shape("turtle")
#x.color("blue")

#x.width(100)
#x.fd(200)
#x.lt(90)
#x.rt(200)
#x.bk(200)
#x.circle(100)
#x.speed
#x.up()
#x.down()

#x.reset()

#for i in range(1000):
     #x.circle(3*i)
     #x.left(10)
     #x.speed(0)

ground.width(10)
ground.right(90)
ground.fd(350)
ground.color("brown")
ground.left(90)
ground.fd(350)
ground.bk(700)
stem.width(10)
stem.color("green")
stem.right(90)
stem.fd(350)
y.left(90)
z.left(180)
a.left(270)
b.left(45)
c.left(135)
d.left(225)
e.left(315)
for i in range(10):
     x.color("white")
     x.circle(7*i)
     x.speed(0)
     y.color("white")
     y.circle(7*i)
     y.speed(0)
     z.color("white")
     z.circle(7*i)
     z.speed(0)
     a.color("white")
     a.circle(7*i)
     a.speed(0)
     
#for i in range(1):
  #   w.color("white")
 #    w.right(90)
 #    w.forward(127)
 #    w.left(90)
  #   w.circle(127)
for i in range(10):
     b.color("yellow")
     b.circle(7*i)
     b.speed(0)
     c.color("yellow")
     c.circle(7*i)
     c.speed(0)
     d.color("yellow")
     d.circle(7*i)
     d.speed(0)
     e.color("yellow")
     e.circle(7*i)
     e.speed(0)
     
     
